image: registry.znuny.com/znuny/docker-otrs5ci:latest

services:
  - name: registry.znuny.com/znuny/docker-mysql-utf8:latest
    alias: mysql

stages:
  - deploy

job_deploy_otrs_Znuny4OTRSSecondTicketCreateScreen:
  stage: deploy
  script:
    - git config --global push.default current
    - sh /sync_repo.sh git@github.com:znuny/Znuny4OTRS-SecondTicketCreateScreen.git